<?php
class Customer
{
    public function __construct(
        public readonly ?int $customer_id,
        public readonly string $first_name,
        public readonly string $last_name,
        public readonly string $email,
        public readonly ?string $private_id = null,
        public readonly ?string $password = null,
        public readonly ?string $uuid = null, //GENERATED BY the Repo
        public readonly ?string $data = null, //GENERATED BY the app
        public readonly ?int $company_id = null
    ) {}
}
