<?php
class Customer
{
    public function __construct(
        public readonly ?int $customer_id,
        public readonly string $first_name,
        public readonly string $last_name,
        public readonly string $email,
        public readonly ?string $uuid, //GENERATED BY the Repo
        public readonly ?string $data, //GENERATED BY the app
        public readonly ?int $company_id
    ) {}
}
